const products = [
    {
        id: 388830,
        sellerId: 10009,
        name: "Kinh Thánh",
        description: "Description for product 1",
        price: 350000,
        categoryId: 4,
        categorySlug: "sach-cong-giao",
        quantityStock: 3,
        slug: "kinh-thanh-detail",
        discount: 10,
        shippingFee: "Free",
        size: "20 x 30",
        condition: "new",
        imageUris: [
            "https://static.oreka.vn/250-250_788ec4cf-f498-4b59-9d6c-f99332f362a5",
            "https://static.oreka.vn/250-250_788ec4cf-f498-4b59-9d6c-f99332f362a5",
            "https://static.oreka.vn/250-250_788ec4cf-f498-4b59-9d6c-f99332f362a5",
            "https://static.oreka.vn/250-250_788ec4cf-f498-4b59-9d6c-f99332f362a5",
            "https://static.oreka.vn/250-250_788ec4cf-f498-4b59-9d6c-f99332f362a5",
            "https://giangvien.net/uploads/shops/2024_06/XH34(1).jpg"
        ],
        imageId: "image1",
        commentIds: ["comment1", "comment2"],
        reportID: "report1",
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date('2023-01-01'),
        location: "Hà Nội",
        status: "Mới cứng"
    },
    {
        id: 2,
        sellerId: 102,
        name: "Product 2",
        description: "Description for product 2",
        price: 49.99,
        categories: ["Category 2"],
        quantityStock: 50,
        slug: "product-2",
        discount: 5,
        condition: "used",
        imageUris: [
            "https://static.oreka.vn/250-250_0245c61b-eda5-4497-a6c4-ca2e6059bbfb"
        ],
        imageId: "image2",
        commentIds: ["comment3", "comment4"],
        reportID: "report2",
        createdAt: new Date('2023-02-01'),
        updatedAt: new Date('2023-02-01'),
        location: "Hà Nội",
        status: "out of stock"
    },
    {
        id: 3,
        sellerId: 103,
        name: "Product 3",
        description: "Description for product 3",
        price: 19.99,
        categories: ["Category 3"],
        quantityStock: 200,
        slug: "product-3",
        discount: 15,
        condition: "new",
        imageUris: [
            "https://static.oreka.vn/250-250_29bc19ea-bd04-4ca8-9840-0e9096ccea34"
        ],
        imageId: "image3",
        commentIds: ["comment5", "comment6"],
        reportID: "report3",
        createdAt: new Date('2023-03-01'),
        updatedAt: new Date('2023-03-01'),
        location: "Hà Nội",
        status: "available"
    },
    {
        id: 4,
        sellerId: 104,
        name: "Product 4",
        description: "Description for product 4",
        price: 99.99,
        categories: ["Category 4"],
        quantityStock: 10,
        slug: "product-4",
        discount: 20,
        condition: "new",
        imageUris: [
            "https://static.oreka.vn/250-250_9ce4da5e-dc5d-4e8b-89ae-8e2ae70c3eca"
        ],
        imageId: "image4",
        commentIds: ["comment7", "comment8"],
        reportID: "report4",
        createdAt: new Date('2023-04-01'),
        updatedAt: new Date('2023-04-01'),
        location: "Hà Nội",
        status: "available"
    },
    {
        id: 5,
        sellerId: 105,
        name: "Product 5",
        description: "Description for product 5",
        price: 39.99,
        categories: ["Category 5"],
        quantityStock: 0,
        slug: "product-5",
        discount: 0,
        condition: "used",
        imageUris: [
            "https://static.oreka.vn/250-250_c253b13a-2c68-4a4a-b208-a08d6466697d"
        ],
        imageId: "image5",
        commentIds: ["comment9", "comment10"],
        reportID: "report5",
        createdAt: new Date('2023-05-01'),
        updatedAt: new Date('2023-05-01'),
        location: "Hà Nội",
        status: "out of stock"
    },
    {
        id: 6,
        sellerId: 106,
        name: "Product 6",
        description: "Description for product 6",
        price: 59.99,
        categories: ["Category 6"],
        quantityStock: 150,
        slug: "product-6",
        discount: 10,
        condition: "new",
        imageUris: [
            "https://static.oreka.vn/250-250_407e85d7-003a-40ab-af7c-0caae623da3f"
        ],
        imageId: "image6",
        commentIds: ["comment11", "comment12"],
        reportID: "report6",
        createdAt: new Date('2023-06-01'),
        updatedAt: new Date('2023-06-01'),
        location: "Hà Nội",
        status: "available"
    },
    {
        id: 7,
        sellerId: 107,
        name: "Product 7",
        description: "Description for product 7",
        price: 79.99,
        categories: 4,
        quantityStock: 0,
        slug: "product-7",
        discount: 5,
        condition: "used",
        imageUris: [
            "https://static.oreka.vn/250-250_d150d7ba-fbc1-402c-80eb-fd27b9c51c10"
        ],
        imageId: "image7",
        commentIds: ["comment13", "comment14"],
        reportID: "report7",
        createdAt: new Date('2023-07-01'),
        updatedAt: new Date('2023-07-01'),
        location: "Hà Nội",
        status: "out of stock"
    },
    {
        id: 8,
        sellerId: 108,
        name: "Product 8",
        description: "Description for product 8",
        price: 89.99,
        categories: ["Category 8"],
        quantityStock: 100,
        slug: "product-8",
        discount: 10,
        condition: "new",
        imageUris: [
            "https://static.oreka.vn/250-250_55c9b782-835f-420b-b78e-56f8f985c546"
        ],
        imageId: "image8",
        commentIds: ["comment15", "comment16"],
        reportID: "report8",
        createdAt: new Date('2023-08-01'),
        updatedAt: new Date('2023-08-01'),
        location: "Hà Nội",
        status: "available"
    },
    {
        id: 9,
        sellerId: 109,
        name: "Sách hướng dẫn làm giàu cực nhanh bằng Pi coin",
        description: "Description for product 9",
        price: 9.99,
        categories: ["Category 9"],
        quantityStock: 500,
        slug: "product-9",
        discount: 0,
        condition: "new",
        imageUris: [
            "https://static.oreka.vn/250-250_b92ef463-3483-4ad7-b529-f70073cab520"
        ],
        imageId: "image9",
        commentIds: ["comment17", "comment18"],
        reportID: "report9",
        createdAt: new Date('2023-09-01'),
        updatedAt: new Date('2023-09-01'),
        location: "Hà Nội",
        status: "available"
    },
    {
        id: 10,
        sellerId: 110,
        name: "Product 10",
        description: "Description for product 10",
        price: 69.99,
        categories: ["Category 10"],
        quantityStock: 0,
        slug: "product-10",
        discount: 20,
        condition: "used",
        imageUris: [
            "https://static.oreka.vn/250-250_ce1927fa-b5fb-4bb6-8fee-a51e99ea1021"
        ],
        imageId: "image10",
        commentIds: ["comment19", "comment20"],
        reportID: "report10",
        createdAt: new Date('2023-10-01'),
        updatedAt: new Date('2023-10-01'),
        location: "Hà Nội",
        status: "out of stock"
    },
    {
        id: 388831,
        sellerId: 10009,
        name: 'Sách Cầu Nguyện Hằng Ngày',
        description: "Tuyển tập những lời cầu nguyện cần thiết.",
        price: 150000,
        categoryId: 4,
        categorySlug: "sach-cong-giao",
        quantityStock: 10,
        slug: "cau-nguyen-hang-ngay",
        discount: 0,
        shippingFee: "30000",
        size: "15 x 22",
        condition: "new",
        imageUris: [
          "https://thuviendaminh.net/media/tacpham/hinhanh/IMG_20210330_0020.jpg"
        ],
        imageId: "image2",
        commentIds: [],
        reportID: null,
        createdAt: "2023-02-15T00:00:00.000Z",
        updatedAt: "2023-02-15T00:00:00.000Z",
        location: "Hồ Chí Minh",
        status: "Mới"
      },
      {
        id: 388832,
        sellerId: 10009,
        name: 'Tượng Đức Mẹ Maria',
        description: "Tượng Đức Mẹ Maria bằng gỗ cao cấp.",
        price: 800000,
        categoryId: 5,
        categorySlug: "do-tho-phuong",
        quantityStock: 5,
        slug: "tuong-duc-me-maria",
        discount: 5,
        shippingFee: "Free",
        size: "30 x 50",
        condition: "new",
        imageUris: [
          "https://dieukhacthienquang.com/upload/sanpham/gm40-7558.jpg",
          
        ],
        imageId: "image3",
        commentIds: ["comment3"],
        reportID: null,
        createdAt: "2023-03-20T00:00:00.000Z",
        updatedAt: "2023-03-20T00:00:00.000Z",
        location: "Đà Nẵng",
        status: "Mới"
      },
      {
        id: 388833,
        sellerId: 10009,
        name: 'Chuỗi Mân Côi',
        description: "Chuỗi Mân Côi bằng đá tự nhiên.",
        price: 250000,
        categoryId: 4,
        categorySlug: "do-tho-phuong",
        quantityStock: 20,
        slug: "chuoi-man-coi",
        discount: 15,
        shippingFee: "20000",
        size: "Standard",
        condition: "new",
        imageUris: [
          "https://phongthuyvanbe.com/wp-content/uploads/2020/12/chuoi-man-coi-go-mun-1-800x800.jpg"
        ],
        imageId: "image4",
        commentIds: [],
        reportID: null,
        createdAt: "2023-04-10T00:00:00.000Z",
        updatedAt: "2023-04-10T00:00:00.000Z",
        location: "Cần Thơ",
        status: "Mới"
      },
      {
        id: 388834,
        sellerId: 10009,
        name: "Áo Lễ Linh Mục",
        description: "Áo lễ linh mục cao cấp, nhiều màu sắc.",
        price: 1200000,
        categoryId: 4,
        categorySlug: "ao-le-linh-muc",
        quantityStock: 2,
        slug: "ao-le-linh-muc",
        discount: 0,
        shippingFee: "Free",
        size: "L, XL",
        condition: "new",
        imageUris: [
          "https://tuongthoconggiao.com/wp-content/uploads/2020/07/nen-thanh-gia-15cm-1.jpg"
        ],
        imageId: "image5",
        commentIds: [],
        reportID: null,
        createdAt: "2023-05-05T00:00:00.000Z",
        updatedAt: "2023-05-05T00:00:00.000Z",
        location: "Huế",
        status: "Mới"
      },
        {
        id: 388835,
        sellerId: 10009,
        name: "Ngôn ngữ của chúa",
        description: "Một câu chuyện rất hay",
        price: 50000,
        categoryId: 4,
        categorySlug: "sach-cong-giao",
        quantityStock: 50,
        slug: "ngon-ngu-cua-chua",
        discount: 20,
        shippingFee: "Free ship",
        size: "Tiêu chuẩn",
        condition: "new",
        imageUris: [
            "https://down-vn.img.susercontent.com/file/27470c43cfabb1eb44a57ad1228570cc"
        ],
        imageId: "image6",
        commentIds: [],
        reportID: null,
        createdAt: "2023-06-01T00:00:00.000Z",
        updatedAt: "2023-06-01T00:00:00.000Z",
        location: "Kiêng Giang",
        status: "Mới"
      },
    {
            id: 388836,
            sellerId: 10009,
            name: "Cửu Long quái sự ký",
            description: "Description for product 9",   
            price: 200000,
            categoryId: 2,
            categorySlug: "mua-ban-sach",
            quantityStock: 100,
            slug: "cuu-long-quai-su-ky",
            discount: 10,
            shippingFee: "Free ship",
            size: "Tiêu chuẩn",
            condition: "new",
            imageUris: [
                "https://datdongradio.com/upload/images/TRUYEN-DAI/CLQSK/cuu-long-quai-su-ky-thien-10-thuy-dao-ham-luong-nghe-truyen-ma-audio-nguyen-huy-chuyen-ma.jpg"
            ],
            imageId: "image7",
            commentIds: [],
            reportID: null,
            createdAt: "2023-07-01T00:00:00.000Z",
            updatedAt: "2023-07-01T00:00:00.000Z",
            location: "Kiên Giang",
            status: "Mới"
            },
            {
                id: 388837,
                sellerId: 10009,
                name: "Cửu Long quái sự ký thiên 2",
                description: "Description for product 9",   
                price: 350000,
                categoryId: 2,
                categorySlug: "mua-ban-sach",
                quantityStock: 100,
                slug: "cuu-long-quai-su-ky",
                discount: 10,
                shippingFee: "Free ship",
                size: "Tiêu chuẩn",
                condition: "new",
                imageUris: [
                    "https://i0.wp.com/radiosach.com/public/upload/cover/cuu-long-quai-su-ky.jpg"
                ],
                imageId: "image8",
                commentIds: [],
                reportID: null,
                createdAt: "2023-07-01T00:00:00.000Z",
                updatedAt: "2023-07-01T00:00:00.000Z",
                location: "Kiên Giang",
                status: "Mới"
                },
];

module.exports = products;